@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mrcrayfish.guns.datagen;

import com.mojang.blaze3d.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;